name: Build
run-name: ${{ github.actor }} start build webApp ğŸš€
on:
  pull_request:
    types: [synchronize, closed, opened]
    branches:
      - dev
      - master

jobs:
  Web-App-Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger web-app build on ${{ github.event_name }} event."
      - run: echo "Checkout to yourbranch ${{ github.ref }}."

      - name: Check out repository code
          uses: actions/checkout@v3

      - name: Install the dependencies
        - run: echo " Installing the dependancies on ${{ runner.os }} server hosted by GitHub!"
        - run: yarn install
      - run: echo "ğŸ This job's status is ${{ job.status }}."